name = "moonlight-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# APP_TOKEN is set via: npx wrangler secret put APP_TOKEN

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "2927eef779f343eea0fea0bd348fde9e"
